# -*- coding: utf-8 -*-
"""Say "Hello, World!" With Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_jZdrKnB-8cUxiy7xMBmZkb73V2By2ut
"""

if __name__ == '__main__':
    print('Hello, World!')